### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 23rd July

### ISSUE THREAD

**Issue by jpgough-ms** [finos/architecture-as-code#308]
## Date

Tuesday 23rd July - 11:00 EST / 16:00 BST

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |
| Christopher Avalos | Individual | |
| Brad Davis | Red Hat | |
| Dean Ogden | | |
| Balaji Siva | Red Hat | |
| Wilson Sinclair | | |
| Oli Bage | LSEG | |
| Frank Schawillie | RBC | |
|James McLeod | | |
|Pete Suggitt | | |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve [previous meeting minutes](https://github.com/finos/architecture-as-code/issues/288)
- [x] [Recap of CALM / AasC](https://github.com/finos/devops-automation/files/13120631/2023-10-24.pdf) and purpose for new joiners if needed (@jpgough-ms  / 5mins)
- [x] Quick fire updates
   - OSFF New York talks submitted 
   - RedHat discussions and reviews of code and documentation
   - FINOS Leadership team working through feedback
- [x] Update on resiliency requirement domain document (5 mins)
- [x] Approach for new domains
   - Multiple new domains proposed: Security, Observability, Resiliency 
   - Requirements gathering groups
   - Design for implementation in the CALM model (#310)
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/architecture-as-code/

**Project Board:** https://github.com/orgs/finos/projects/98

**Mailing List:** Email devops-automation+subscribe@finos.org to subscribe to our mailing list

**Comment by jpgough-ms** [comment]
In attendance: @jpgough-ms

**Comment by grahampacker-ms** [comment]
Graham Packer / Morgan Stanley

**Comment by willosborne** [comment]
Will Osborne / Morgan Stanley

**Comment by aidanm3341** [comment]
Aidan McPhelim / Morgan Stanley

**Comment by markusjnagel** [comment]
Meg Foley and Markus Nagel, both at Red Hat :wave:

**Comment by daddario85** [comment]
Dario Bevilacqua / LSEG

**Comment by djohnston89** [comment]
David Johnston - Red Hat - Working with Denis Coffaro on a joint session for the upcoming NYC Open Source Finance Forum.

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by grahampacker-ms** [comment]
Minutes of meeting

**FINOS Meeting:** July 23, 2024
**Commenced:** 16:03 BST
**Introduction / FINOS Disclaimer:** Done
**Agenda & Attendance noted:** #308 - Done
**Previous minutes approved by attendees and closed out (Issue #288):** - Approved

**Recap of CALM / AaC:** Done
**ACTION - @jpgough-ms to schedule a deep dive session on CALM aimed at new contributors**


**Quick fire updates:**
**OSFF New York talks submitted:**

- specifically CALM Security domains

**RedHat discussions and reviews of code and documentation:**
- Attendees from Trusted Software Supply Chain and Backstage groups from Red Hat
- Investigating possibility of partnership between Red Hat and the AasC group
- May be Red Hat LLM patterns that could leverage CALM

**FINOS Leadership team working through feedback:** Done


**Update on resiliency requirement domain document (5 mins):
ACTION -  Postponed to next session due to missing key contributors**


**Approach for new domains:**
- Initial Proposal submitted by Will Osborne. Not a final solution.
- Aim to keep the core of CALM simple, reduce opinion, keep as flexible as possible
- Create ability to provide external JSON schemas to extend CALM with new features without adding the opinions of extention to the core schema
- **Call for action: provide feedback on the proposal, identify core features vs. extendible features**


**AOB, Q&A & Adjourn (5mins)**
**TraderX Sprint - @karlmoll** 
- Introduction to the TraderX Tech Sprint for new attendees
- Signposted the CALM Security Domain issue on the TraderX project

**Communication methods:**
- Stick to the AasC GitHub issues/discussions, possible Slack channel in future, but some may not be able to use Slack due to employer restrictions

Q: Christopher Avalos - Has there been analysis of commercial products that offers similar solutions?
A:
@jpgough-ms - Spoken to Simon Brown on C4 + creator of  C4 Interflow. Yan Tordoff - looked at other options, but they were rejected
**ACTION - @jpgough-ms  to check if there's documentation on rejected comercial options and how we document this in future (ADRs)**
@yt-ms - Interoperability Key, translators already in progress.
Oli Bage - CALM is being build with Financial Services controls in mind, comercial solutions too generic but may be able to leverege aspects of them
@karlmoll - FINOS AI readiness SIG working on a architectural governance, will need to be machine understandable to certify compliance. CALM may be used for this. Coming with Financial Services use cases/controls in mind.

@karlmoll  - Microsoft Radias group is looking at TraderX, there may be a valuable conversation possible here
**ACTION - @karlmoll to make introduction for James Gough to the MS Radias group**


**Adjourned:** 17:00

**Comment by charleyalpha789** [comment]
In attendance - Christopher Avalos

**Comment by rocketstack-matt** [comment]
Approved at https://github.com/finos/architecture-as-code/issues/360
