### ISSUE TITLE
Generate does not output placeholders for boolean properties

### ISSUE THREAD

**Issue by willosborne** [finos/architecture-as-code#353]
### Steps to Reproduce:
Add a boolean field to a node, relationship or metadata object

e.g.

```json
{
    "type": "object",
    "properties": {
          "propertyBoolean": {
                  "type": "boolean"
           }
      }
}
```

### Expected Result:
```json
{
     "propertyBoolean": "{{ PROPERTY_BOOLEAN }}"
}
```

### Actual Result:
```json
{}
```

### Environment:
Latest version of CLI

### Additional Context:
Placeholder values are tricky here. We can't just output `false` as this could be dangerous.
We should consider a warning to use enums instead of booleans.
Suggested fix for booleans is:
- output a string placeholder (will fail validation)
- emit a warning saying to use enums instead 
- add a spectral rule to also emit this warning on pattern files

**Comment by rocketstack-matt** [comment]
I was reviewing the newly launched tour.json-schema.org (which is very cool btw, going to link it from our docs).

So it turns out we have another option here by [combining boolean and null type](https://tour.json-schema.org/content/02-Primitive-Types/09-Combining-Types).

If we defined the type as 
```json
{
  "type": ["boolean", "null"]
}
```
then we could use a null placeholder, the schema would be valid but we could warn the null placeholder.
